Repository GlueOps/provisioner-node-setup, pull requests merged in 2025-05, with the labels that each got.

#20 update comments and other refactoring
  playbooks/server-install.yml
  templates/cache.conf.j2
  templates/docker-compose.yaml.j2
  templates/provisioner-cache.service.j2
Labels: Review effort 2/5

#19 Feat/add docker runtime and provisioner-cache using nginx
  playbooks/server-install.yml
  templates/cache.conf.j2
  templates/docker-compose.yaml.j2
  templates/provisioner-cache.service.j2
Labels: Review effort 3/5

#22 fix: remove invalid --no-cache flag from docker compose up command
  templates/provisioner-cache.service.j2
Labels: Review effort 1/5

#23 feat: Add PRCHECKLIST using Pull Request Checklist Buddy
  .github/configs/labeler.yml
  PRCHECKLIST
Labels: enhancement, Review effort 1/5, include-in-release-notes, minor, patch
